#!/bin/bash

exec 2>&1

set -ex

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

if ! grep "=== SETUP COMPLETE ===" /var/log/irondb-setup.log
then
  uuid=$(cat /opt/circonus/node_uuid.txt)
  /opt/circonus/bin/setup-irondb -a "{{sys.ip}}" -n ${uuid} -c "{{cfg.default_check_name}}" -u "{{cfg.default_check_uuid}}"
fi

# disable and remove systemd service since we are using a Habitat service
if systemctl status circonus-irondb.service
then
  systemctl stop circonus-irondb.service
  systemctl disable circonus-irondb.service
  rm /lib/systemd/system/circonus-irondb.service
fi

pushd /opt/circonus/etc
  ln -fs /opt/circonus/topology
  ln -fs {{pkg.svc_config_path}}/licenses.conf
  ln -fs {{pkg.svc_config_path}}/irondb.conf
  ln -fs {{pkg.svc_config_path}}/topology_snippet.conf
popd

active_topology_hash=$(/opt/circonus/bin/snowthimport -c /opt/circonus/etc/irondb.conf -f /opt/circonus/etc/topology | awk '{print $3}')
cat > /opt/circonus/etc/topology_snippet.conf <<EOF
<topology path="/opt/circonus/etc/irondb-topo"
          active="${active_topology_hash}"
          next=""
          redo="/irondb/redo/{node}"
/>
EOF
